mdedit:
  toolbar:

    -
      css_class: icon icon-bold
      tooltip: "@mdedit.toolbar.bold"
      bind_key:
        win: 'Ctrl-B'
        mac: 'Command-B'
      command: cmdBold

    -
      css_class: icon icon-italic
      tooltip: "@mdedit.toolbar.italic"
      bind_key:
        win: 'Ctrl-I'
        mac: 'Command-I'
      command: cmdItalic

    -
      css_class: mdedit-toolbar__sep

    -
      css_class: icon icon-link
      tooltip: "@mdedit.toolbar.link"
      bind_key:
        win: 'Ctrl-L'
        mac: 'Command-L'
      command: cmdLink

    #-
    #  css_class: mdedit-toolbar__quote
    #  tooltip: "@mdedit.toolbar.quote"
    #  bind_key:
    #    win: 'Ctrl-Q'
    #    mac: 'Command-Q'
    #  command: cmdQuote

    -
      css_class: icon icon-picture
      tooltip: "@mdedit.toolbar.image"
      bind_key:
        win: 'Ctrl-G'
        mac: 'Command-G'
      command: cmdImage

    -
      css_class: icon icon-attach
      tooltip: "@mdedit.toolbar.attach"
      command: cmdAttach

    -
      css_class: mdedit-toolbar__sep

    -
      css_class: icon icon-list-numbered
      tooltip: "@mdedit.toolbar.ol"
      bind_key:
        win: 'Ctrl-O'
        mac: 'Command-O'
      command: cmdOl

    -
      css_class: icon icon-list-bullet
      tooltip: "@mdedit.toolbar.ul"
      bind_key:
        win: 'Ctrl-U'
        mac: 'Command-U'
      command: cmdUl

    #-
    #  css_class: mdedit-toolbar__header
    #  tooltip: "@mdedit.toolbar.header"
    #  bind_key:
    #    win: 'Ctrl-H'
    #    mac: 'Command-H'
    #  command: cmdHeading

    -
      css_class: mdedit-toolbar__sep

    #-
    #  css_class: mdedit-toolbar__cut
    #  tooltip: "@mdedit.toolbar.cut"
    #  command: cmdCut

    -
      css_class: icon icon-help
      tooltip: "@mdedit.toolbar.help"
      bind_key:
        win: 'F1'
        mac: 'F1'
      command: cmdHelp
