medialinks:

  #
  # Array of enabled providers, or `true` for all.
  #
  content: true

  #
  # Providers definition
  #
  # name:
  #   match     - regexp or array of regexps to check link
  #   fetch     - function(require, url, callback) to get provider data
  #               for template. Should be string (function body)
  #   template  - lodash template to render fetched data
  #
  providers:

    youtube:
      name: YouTube
      home: http://www.youtube.com/

      match:
        - /https?://(www\.)?youtube\.com/watch.*/i
        - /https?://(www\.)?youtube\.com/playlist.*/i
        - /https?://youtu\.be/.*/i

      fetch: |
        var request = require('request');

        request('http://www.youtube.com/oembed?url=' + url, function (err, response, body) {
          if (err) {
            callback(err);
            return;
          }

          var oembed;
          try {
            oembed = JSON.parse(body);
          } catch (err) {
            callback(err);
            return;
          }

          var video_url = oembed.html.match(/src="([^"]+)/i)[1];
          video_url = video_url.replace(/^https?:/, '');

          var result = {
            provider: 'youtube',
            src: url,
            video_url: video_url,
            thumb: oembed.thumbnail_url.replace(/^https?:/, '').replace(/[a-z0-9]+\.jpg$/, 'mqdefault.jpg'),
            video_height: oembed.height,
            video_width: oembed.width,
            title: oembed.title
          };

          callback(null, result);
        });

      template: |
        <div class="medialink-video medialink-<%= self.provider %>" data-nd-type="medialink" data-nd-rule="<%= self.provider %>" data-nd-src="<%= self.src %>" data-nd-cache=\'{ url: "<%= self.video_url %>" }\'>
          <div class="embed-responsive embed-responsive-<%= self.video_width/self.video_height > 1.5 ? '16by9' : '4by3' %>">
            <iframe src="<%= self.video_url %>" allowfullscreen></iframe>
          </div>
        </div>

      stub: |
        <div class="medialink-video medialink-video__m-stub medialink-youtube" data-nd-type="medialink" data-nd-rule="youtube">
          <div class="embed-responsive embed-responsive-16by9">
          </div>
        </div>

    vimeo:
      name: Vimeo
      home: https://vimeo.com/

      match: /https?://(.+\.)?vimeo\.com/.*/i

      fetch: |
        var request = require('request');

        request('http://vimeo.com/api/oembed.json?url=' + url, function (err, response, body) {
          if (err) {
            callback(err);
            return;
          }

          var oembed;
          try {
            oembed = JSON.parse(body);
          } catch (err) {
            callback(err);
            return;
          }

          var video_url = oembed.html.match(/src="([^"]+)/i)[1];
          video_url = video_url.replace(/^https?:/, '');

          var result = {
            provider: 'vimeo',
            src: url,
            video_url: video_url,
            thumb: oembed.thumbnail_url.replace(/^https?:/, '').replace(/_[0-9]+\.jpg$/, '_200.jpg'),
            video_height: oembed.height,
            video_width: oembed.width,
            title: oembed.title
          };

          callback(null, result);
        });

      template: |
        <div class="medialink-video medialink-<%= self.provider %>" data-nd-type="medialink" data-nd-rule="<%= self.provider %>" data-nd-src="<%= self.src %>" data-nd-cache=\'{ url: "<%= self.video_url %>" }\'>
          <div class="embed-responsive embed-responsive-<%= self.video_width/self.video_height > 1.5 ? '16by9' : '4by3' %>">
            <iframe src="<%= self.video_url %>" allowfullscreen></iframe>
          </div>
        </div>

      stub: |
        <div class="medialink-video medialink-video__m-stub medialink-vimeo" data-nd-type="medialink" data-nd-rule="vimeo">
          <div class="embed-responsive embed-responsive-16by9">
          </div>
        </div>

    rutube:
      name: Rutube
      home: http://rutube.ru/

      match: /https?://(.+\.)?rutube\.ru/.*/i

      fetch: |
        var request = require('request');

        request('http://rutube.ru/api/oembed/?format=json&url=' + url, function (err, response, body) {
          if (err) {
            callback(err);
            return;
          }

          var oembed;
          try {
            oembed = JSON.parse(body);
          } catch (err) {
            callback(err);
            return;
          }

          var video_url = oembed.html.match(/src="([^"]+)/i)[1];
          video_url = video_url.replace(/^https?:/, '');

          var result = {
            provider: 'rutube',
            src: url,
            video_url: video_url,
            thumb: oembed.thumbnail_url.replace(/^https?:/, '').replace(/\?.+$/, '?size=s'),
            video_height: oembed.height,
            video_width: oembed.width,
            title: oembed.title
          };

          callback(null, result);
        });

      template: |
        <div class="medialink-video medialink-<%= self.provider %>" data-nd-type="medialink" data-nd-rule="<%= self.provider %>" data-nd-src="<%= self.src %>" data-nd-cache=\'{ url: "<%= self.video_url %>" }\'>
          <div class="embed-responsive embed-responsive-<%= self.video_width/self.video_height > 1.5 ? '16by9' : '4by3' %>">
            <iframe src="<%= self.video_url %>" allowfullscreen></iframe>
          </div>
        </div>

      stub: |
        <div class="medialink-video medialink-video__m-stub medialink-rutube" data-nd-type="medialink" data-nd-rule="rutube">
          <div class="embed-responsive embed-responsive-16by9">
          </div>
        </div>
