menus:
  common:
    admin:
      dashboard:
        to: admin.dashboard
        priority: 500
        check_permissions: true

  admin:
    navbar:
      system:
        submenu:
          settings:
            submenu:
              options:
                to: admin.core.global_settings.show
                params: {}
