menus:
  common:
    admin:
      dashboard:
        to: admin.core.dashboard.show
        priority: 500
        check_permissions: true

  admin:
    navbar:
      core:
        to: admin.core.dashboard.show
        submenu:
          dashboard:
            to: admin.core.dashboard.show
            submenu:
              show:
                to: admin.core.dashboard.show

          global_setting_groups:
            to: admin.core.global_setting_groups.index
            submenu:
              index:
                to: admin.core.global_setting_groups.index
