menus:
  common:
    admin:
      dashboard:
        to: admin.dashboard
        priority: 500
        check_permissions: true

  admin:
    navbar:
      system:
        to: admin.dashboard
    leftpanel:
      settings:
        to: admin.settings.global.index
