menus:
  common:
    topnav:
      admin:
        to: admin.dashboard
        priority: 500
        check_permissions: true

  admin:
    topnav:
      settings:
        to: admin.settings.global.index
    leftpanel:
      settings:
        to: admin.settings.global.index
