menus:
  admin:
    navbar:
      core:
        to: admin.core.dashboard
        submenu:
          dashboard:
            to: admin.core.dashboard

          global_settings:
            to: admin.core.global_settings.index

          rebuild:
            to: admin.core.rebuild
