parser:
  cleanup:
    root:
      children: [ p, a, img, group-header, group-top-level-block, cut, spoiler, blockquote ]

    h1:
      group: header
      children: text
      remove_empty: true
    h2:
      group: header
      children: text
      remove_empty: true
    h3:
      group: header
      children: text
      remove_empty: true
    h4:
      group: header
      children: text
      remove_empty: true
    h5:
      group: header
      children: text
      remove_empty: true

    strong:
      group: simple
      children: [ text, group-simple, a, img ]
      remove_empty: true
      merge_same: true
    em:
      group: simple
      children: [ text, group-simple, a, img ]
      remove_empty: true
      merge_same: true
    del:
      group: simple
      children: [ text, group-simple, a, img ]
      remove_empty: true
      merge_same: true
    sub:
      group: simple
      children: [ text, group-simple, a, img ]
      remove_empty: true
      merge_same: true
    sup:
      group: simple
      children: [ text, group-simple, a, img ]
      remove_empty: true
      merge_same: true

    code:
      group: simple
      children: [ text ]
      remove_empty: true

    p:
      children: [ text, group-simple, a, img ]
    a:
      children: [ text, group-simple, img ]
      attributes: href
      remove_empty: true
    img:
      attributes:
        - src
        - title
        - alt
        - size: [ orig, md, sm ]
        - align: [ left, center, right ]

    table:
      group: top-level-block
      children: tr
      remove_empty: true
    tr:
      children: [ th, td ]
      remove_empty: true
    th:
      children: [ text, group-simple, p, a, ul, ol ]
      attributes:
        colspan: \d+
        rowspan: \d+
    td:
      children: [ text, group-simple, p, a, ul, ol ]
      attributes:
        colspan: \d+
        rowspan: \d+

    ul:
      group: top-level-block
      children: li
      remove_empty: true
    ol:
      group: top-level-block
      children: li
      remove_empty: true
    li:
      children: [ ul, ol, text, group-simple, p, a, img ]
      remove_empty: true

    pre:
      group: top-level-block
      children: [ code ]

    cut:
      children: text

    spoiler:
      children: [ text, group-simple, p, a, img, group-top-level-block ]
      attributes: title
      remove_empty: true

    blockquote:
      children: [ text, group-simple, p, a, img, group-top-level-block ]
      attributes: [ author, time ]
      remove_empty: true
