bind:
  admin:
    mount: /admin


router:
  map:
    admin.core.dashboard:
      "/": ~

    admin.core.global_settings.show:
      "/settings(/{group})":
        group: /\S+/

    core.assets:
      "/assets/{path}":
        path: /.+/
        responder: bin

    core.static:
      "/{file}":
        file: /favicon.ico|robots.txt|snippet.png/
        responder: bin
