bind:
  admin:
    mount: /admin


router:
  map:
    admin.core.dashboard.show:
      "/": ~

    admin.core.settings_global.groups.show:
      "/settings":

    admin.core.settings_global.settings.edit:
      "/settings/{group}":
        group: /\S+/

    core.assets:
      "/assets/{path}":
        path: /.+/
        responder: bin

    core.static:
      "/{file}":
        file: /favicon.ico|robots.txt|snippet.png/
        responder: bin
