bind:
  admin:
    mount: /admin


router:
  http.get:
    admin.core.dashboard.show:
      "/": ~

    admin.core.global_setting_groups.index:
      "/settings":

    admin.core.global_setting_groups.edit:
      "/settings/{group}":
        group: /\S+/

  bin:
    core.assets:
      "/assets/{path}":
        path: /.+/

    core.static:
      "/{file}":
        file: /favicon.ico|robots.txt|snippet.png/
