bind:
  admin:
    mount: /admin


router:
  http.get:
    admin.core.dashboard:
      "/": ~

    admin.core.global_settings.index:
      "/core/global_settings":

    admin.core.global_settings.edit:
      "/core/global_settings/{group}":
        group: /\S+/

  bin:
    core.assets:
      "/assets/{path}":
        path: /.+/

    core.static:
      "/{file}":
        file: /favicon.ico|robots.txt|snippet.png/

    core.gridfs:
      "/files/{bucket}":
        bucket: /[0-9a-fA-F]{24}(_[0-9a-zA-Z]+)?/
