router:
  map:
    admin.dashboard:
      "/": ~
    admin.settings.global.index:
      "/settings": ~
    admin.settings.global.edit:
      "/settings/{id}":
        id: /\w+/

    assets:
      "/{path}":
        path: /.+/
    static:
      "/{file}":
        file: /favicon.ico|robots.txt|snippet.png/
