bind:
  admin:
    mount: /admin


router:
  http.get:
    admin.core.dashboard:
      "/": ~

    admin.core.global_settings.index:
      "/core/global_settings":

    admin.core.global_settings.edit:
      "/core/global_settings/{group}":
        group: /\S+/

    admin.core.rebuild:
      "/rebuild": ~

    common.robots:
      "/robots.txt": ~

    common.sitemap:
      "/sitemap.xml": ~

  bin:
    core.assets:
      "/assets/{path}":
        path: /.+/

    core.static:
      "/{file}":
        file: /favicon.ico|snippet.png/

    core.gridfs:
      "/files/{bucket}":
        bucket: /.+/
