router:
  map:
    admin.dashboard:
      "/dashboard": ~
    admin.settings.global.index:
      "/settings": ~
    admin.settings.global.group.show:
      "/settings/{id}":
        id: /\w+/

    assets:
      "/{path}":
        path: /.+/
    static:
      "/{file}":
        file: /favicon.ico|robots.txt|snippet.png/

listen:
  admin:
    mount: /admin
  assets:
    mount: /assets
