bind:
  admin:
    mount: /admin


router:
  map:
    admin.dashboard:
      "/": ~

    #admin.settings.global.index:
    #  "/settings": ~

    #admin.settings.global.edit:
    #  "/settings/{id}":
    #    id: /\w+/

    core.assets:
      "/assets/{path}":
        path: /.+/
        responder: bin

    core.static:
      "/{file}":
        file: /favicon.ico|robots.txt|snippet.png/
        responder: bin
