parser:
  emojis:
    named:
      smile: 😄
      smiley: 😃
      grinning: 😀
      blush: 😊
      wink: 😉
      heart_eyes: 😍
      kissing_heart: 😘
      kissing_closed_eyes: 😚
      kissing: 😗
      kissing_smiling_eyes: 😙
      stuck_out_tongue_winking_eye: 😜
      stuck_out_tongue_closed_eyes: 😝
      stuck_out_tongue: 😛
      flushed: 😳
      grin: 😁
      pensive: 😔
      relieved: 😌
      unamused: 😒
      disappointed: 😞
      persevere: 😣
      cry: 😢
      joy: 😂
      sob: 😭
      sleepy: 😪
      disappointed_relieved: 😥
      cold_sweat: 😰
      sweat_smile: 😅
      sweat: 😓
      weary: 😩
      tired_face: 😫
      fearful: 😨
      scream: 😱
      angry: 😠
      rage: 😡
      confounded: 😖
      laughing: 😆
      satisfied: 😆
      yum: 😋
      mask: 😷
      sunglasses: 😎
      sleeping: 😴
      dizzy_face: 😵
      astonished: 😲
      worried: 😟
      frowning: 😦
      anguished: 😧
      smiling_imp: 😈
      open_mouth: 😮
      neutral_face: 😐
      confused: 😕
      hushed: 😯
      no_mouth: 😶
      innocent: 😇
      smirk: 😏
      expressionless: 😑
      smiley_cat: 😺
      smile_cat: 😸
      heart_eyes_cat: 😻
      kissing_cat: 😽
      smirk_cat: 😼
      scream_cat: 🙀
      crying_cat_face: 😿
      joy_cat: 😹
      pouting_cat: 😾
      sparkles: ✨
      cat: 🐱
      mouse: 🐭
      cow: 🐮
      monkey_face: 🐵
      star: ⭐
      zap: ⚡
      umbrella: ☔
      hourglass: ⌛
      watch: ⌚
      coffee: ☕
      negative_squared_cross_mark: ❎
      white_check_mark: ✅
      x: ❌
      exclamation: ❗
      question: ❓
      grey_exclamation: ❕
      grey_question: ❔
      heavy_plus_sign: ➕
      heavy_minus_sign: ➖
      heavy_division_sign: ➗
      black_medium_small_square: ◾
      white_medium_small_square: ◽
      black_circle: ⚫
      white_circle: ⚪
      white_large_square: ⬜
      black_large_square: ⬛

    aliases:
      # Emoticons -> Emoji mapping.
      mad:
        - '>:('
        - '>:-('
      blush:
        - :")
        - :-")
      broken_heart:
        - </3
        - <\3
      confused:
        # disabled because of conflicts with links
        # - :\
        # - :/
        - :-\
        - :-/
      cry:
        - :'(
        - :'-(
        - :,(
        - :,-(
      frowning:
        - :(
        - :-(
      heart:
        - <3
      imp:
        - ']:('
        - ']:-('
      innocent:
        - o:)
        - O:)
        - o:-)
        - O:-)
        - 0:)
        - 0:-)
      joy:
        - :')
        - :'-)
        - :,)
        - :,-)
        - :'D
        - :'-D
        - :,D
        - :,-D
      kissing:
        - :*
        - :-*
      laughing:
        - x-)
        - X-)
      neutral_face:
        - :|
        - :-|
      open_mouth:
        - :o
        - :-o
        - :O
        - :-O
      rage:
        - :@
        - :-@
      smile:
        - :D
        - :-D
      smiley:
        - :)
        - :-)
      smiling_imp:
        - ']:)'
        - ']:-)'
      sob:
        - :,'(
        - :,'-(
        - ;(
        - ;-(
      stuck_out_tongue:
        - :P
        - :-P
      sunglasses:
        - 8-)
        - B-)
      sweat:
        - ',:('
        - ',:-('
      sweat_smile:
        - ',:)'
        - ',:-)'
      unamused:
        - :s
        - :-S
        - :z
        - :-Z
        - :$
        - :-$
      wink:
        - ;)
        - ;-)
