parser:
  sanitizer:

    default:

      root:
        children:
          group_block: true
      p:
        group: block
        children:
          group_inline: true
        remove_empty: true
      text:
        group: inline
        children: false # skip children tags check
        attributes: false # skip attributes check

    emphasis:

      strong:
        group: inline
        children:
          group_inline: true
        remove_empty: true
      em:
        group: inline
        children:
          group_inline: true
        remove_empty: true
      s:
        group: inline
        children:
          group_inline: true
        remove_empty: true

    links:

      a:
        group: inline
        children:
          group_inline: true
          a: false
        attributes:
          title: true
          href: true
          data-nd-internal: true
          data-nd-auto: true
        remove_empty: true

    images:

      img:
        group: inline
        attributes:
          src: true
          alt: true
          title: true

    lists:

      ul:
        group: block
        children:
          li: true
        remove_empty: true
      ol:
        group: block
        children:
          li: true
        remove_empty: true
      li:
        children:
          ul: true
          ol: true
          group_inline: true
        remove_empty: true

    hrs:

      hr:
        group: block

    codes:

      code:
        group: inline
        children: false   # it will kill fenced blocks highlight in other case
        attributes: false # skip attributes check

      pre:
        group: block
        children:
          code: true
        attributes: false # skip attributes check

    sub:

      sub:
        group: inline

    sup:

      sup:
        group: inline

    headings:

      h1:
        group: block
        children:
          text: true
      h2:
        group: block
        children:
          text: true
      h3:
        group: block
        children:
          text: true
      h4:
        group: block
        children:
          text: true
      h5:
        group: block
        children:
          text: true
      h6:
        group: block
        children:
          text: true

    emojis:

      msg-emoji:
        group: inline
        attributes:
          data-nd-name: true
          data-nd-content: true

    spoilers:

      msg-spoiler:
        group: block
        children:
          group_block: true
        attributes:
          data-nd-title: true
