setting_groups:
  content:
    parent: core

setting_schemas:
  global:
    content_read_marks_expire:
      priority: 10
      group_key: content
      category_key: content_common
      type: number
      default: 30 # 30 days
