setting_schemas:
  global:
    debug_enabled:
      type: boolean
      category: debug

    debug_ip:
      type: string
      category: debug

    debug_users:
      type: users
      category: debug
