setting_groups:
  email:
    parent: core


setting_schemas:
  global:
    email_transport:
      priority: 10
      group_key: email
      category_key: email_common
      type: dropdown
      values:
      - sendmail: sendmail
      - dummy:    dummy    # only log, for debug
      default: sendmail

    email_header_from:
      priority: 20
      group_key: email
      category_key: email_common
      type: string
      default: noreply@example.com
