setting_groups:
  general:
    parent: core


setting_schemas:
  global:
    general_project_name:
      priority: 10
      group_key: general
      category_key: general_common
      type: string
      default: Nodeca

    general_cookies_domain:
      priority: 20
      group_key: general
      category_key: general_common
      type: string

    general_session_expire_hours:
      priority: 30
      group_key: general
      category_key: general_common
      type: number
      default: 168
