---
usergroup:  #

  # Group name

  group_name:
    type: string
    group: Common
    validators:
      required: true
    priority: 0

  # Are members searcheable & counted in stat?

  group_visible:
    type: boolean
    default: true
    group: Common
    priority: 0
