setting_schemas:
  global:
    image_processing_lib:
      type: radio
      values:
        None: 0
        GD: GD
        Magick: ImageMagick
      priority: 0
      group: image

    magick_path:
      type: string
      priority: 0
      group: image
