# This settings are not used directly. Those are taken by apps to generate local sets.

setting_schemas:
  markup:

    markup_cut:
      priority: 10
      type: boolean
      as: cut # rename setting key after fetch
      default: false

    markup_emphasis:
      priority: 10
      type: boolean
      as: emphasis
      default: true

    markup_footnotes:
      priority: 10
      type: boolean
      as: footnotes
      default: true

    markup_headings:
      priority: 10
      type: boolean
      as: headings
      default: true

    markup_images:
      priority: 10
      type: boolean
      as: images
      default: true

    markup_attachments:
      priority: 10
      type: boolean
      as: attachments
      default: true

    markup_links:
      priority: 10
      type: boolean
      as: links
      default: true

    markup_lists:
      priority: 10
      type: boolean
      as: lists
      default: true

    markup_hrs:
      priority: 10
      type: boolean
      as: hrs
      default: true

    markup_codes:
      priority: 10
      type: boolean
      as: codes
      default: true

    markup_medialinks:
      priority: 10
      type: boolean
      as: medialinks
      default: true

    markup_quotes:
      priority: 10
      type: boolean
      as: quotes
      default: true

    markup_emojis:
      priority: 10
      type: boolean
      as: emojis
      default: true

    markup_spoilers:
      priority: 10
      type: boolean
      as: spoilers
      default: true

    markup_sub:
      priority: 10
      type: boolean
      as: sub
      default: true

    markup_sup:
      priority: 10
      type: boolean
      as: sup
      default: true

    markup_tables:
      priority: 10
      type: boolean
      as: tables
      default: true
